//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume
    {
        public int ResumeId { get; set; }
        public string ResumeDocumentPath { get; set; }
        public string UploadedData { get; set; }
        public Nullable<int> SignIn_Fk { get; set; }
    
        public virtual SignUp SignUp { get; set; }
    }
}
